/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedMapRouteImport } from './routes/_authed/map'
import { Route as AuthedLeaderboardRouteImport } from './routes/_authed/leaderboard'
import { Route as AuthedFeedRouteImport } from './routes/_authed/feed'
import { Route as AuthedCoverageRouteImport } from './routes/_authed/coverage'
import { Route as AuthedCommunityRouteImport } from './routes/_authed/community'
import { Route as AuthedProfileIndexRouteImport } from './routes/_authed/profile/index'
import { Route as AuthedProfileUserIdIndexRouteImport } from './routes/_authed/profile/$userId/index'
import { Route as AuthedProfileUserIdMapRouteImport } from './routes/_authed/profile/$userId/map'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/settings.lazy').then((d) => d.Route),
)
const AuthedMapRoute = AuthedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() => import('./routes/_authed/map.lazy').then((d) => d.Route))
const AuthedLeaderboardRoute = AuthedLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/leaderboard.lazy').then((d) => d.Route),
)
const AuthedFeedRoute = AuthedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() => import('./routes/_authed/feed.lazy').then((d) => d.Route))
const AuthedCoverageRoute = AuthedCoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/coverage.lazy').then((d) => d.Route),
)
const AuthedCommunityRoute = AuthedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/community.lazy').then((d) => d.Route),
)
const AuthedProfileIndexRoute = AuthedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/profile/index.lazy').then((d) => d.Route),
)
const AuthedProfileUserIdIndexRoute =
  AuthedProfileUserIdIndexRouteImport.update({
    id: '/profile/$userId/',
    path: '/profile/$userId/',
    getParentRoute: () => AuthedRoute,
  } as any).lazy(() =>
    import('./routes/_authed/profile/$userId/index.lazy').then((d) => d.Route),
  )
const AuthedProfileUserIdMapRoute = AuthedProfileUserIdMapRouteImport.update({
  id: '/profile/$userId/map',
  path: '/profile/$userId/map',
  getParentRoute: () => AuthedRoute,
} as any).lazy(() =>
  import('./routes/_authed/profile/$userId/map.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/community': typeof AuthedCommunityRoute
  '/coverage': typeof AuthedCoverageRoute
  '/feed': typeof AuthedFeedRoute
  '/leaderboard': typeof AuthedLeaderboardRoute
  '/map': typeof AuthedMapRoute
  '/settings': typeof AuthedSettingsRoute
  '/profile/': typeof AuthedProfileIndexRoute
  '/profile/$userId/map': typeof AuthedProfileUserIdMapRoute
  '/profile/$userId/': typeof AuthedProfileUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/community': typeof AuthedCommunityRoute
  '/coverage': typeof AuthedCoverageRoute
  '/feed': typeof AuthedFeedRoute
  '/leaderboard': typeof AuthedLeaderboardRoute
  '/map': typeof AuthedMapRoute
  '/settings': typeof AuthedSettingsRoute
  '/': typeof AuthedIndexRoute
  '/profile': typeof AuthedProfileIndexRoute
  '/profile/$userId/map': typeof AuthedProfileUserIdMapRoute
  '/profile/$userId': typeof AuthedProfileUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_authed/community': typeof AuthedCommunityRoute
  '/_authed/coverage': typeof AuthedCoverageRoute
  '/_authed/feed': typeof AuthedFeedRoute
  '/_authed/leaderboard': typeof AuthedLeaderboardRoute
  '/_authed/map': typeof AuthedMapRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/profile/': typeof AuthedProfileIndexRoute
  '/_authed/profile/$userId/map': typeof AuthedProfileUserIdMapRoute
  '/_authed/profile/$userId/': typeof AuthedProfileUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/community'
    | '/coverage'
    | '/feed'
    | '/leaderboard'
    | '/map'
    | '/settings'
    | '/profile/'
    | '/profile/$userId/map'
    | '/profile/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/community'
    | '/coverage'
    | '/feed'
    | '/leaderboard'
    | '/map'
    | '/settings'
    | '/'
    | '/profile'
    | '/profile/$userId/map'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/community'
    | '/_authed/coverage'
    | '/_authed/feed'
    | '/_authed/leaderboard'
    | '/_authed/map'
    | '/_authed/settings'
    | '/_authed/'
    | '/_authed/profile/'
    | '/_authed/profile/$userId/map'
    | '/_authed/profile/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/map': {
      id: '/_authed/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthedMapRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/leaderboard': {
      id: '/_authed/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthedLeaderboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/feed': {
      id: '/_authed/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthedFeedRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/coverage': {
      id: '/_authed/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof AuthedCoverageRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/community': {
      id: '/_authed/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthedCommunityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile/': {
      id: '/_authed/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthedProfileIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile/$userId/': {
      id: '/_authed/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId/'
      preLoaderRoute: typeof AuthedProfileUserIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile/$userId/map': {
      id: '/_authed/profile/$userId/map'
      path: '/profile/$userId/map'
      fullPath: '/profile/$userId/map'
      preLoaderRoute: typeof AuthedProfileUserIdMapRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCommunityRoute: typeof AuthedCommunityRoute
  AuthedCoverageRoute: typeof AuthedCoverageRoute
  AuthedFeedRoute: typeof AuthedFeedRoute
  AuthedLeaderboardRoute: typeof AuthedLeaderboardRoute
  AuthedMapRoute: typeof AuthedMapRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedProfileIndexRoute: typeof AuthedProfileIndexRoute
  AuthedProfileUserIdMapRoute: typeof AuthedProfileUserIdMapRoute
  AuthedProfileUserIdIndexRoute: typeof AuthedProfileUserIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCommunityRoute: AuthedCommunityRoute,
  AuthedCoverageRoute: AuthedCoverageRoute,
  AuthedFeedRoute: AuthedFeedRoute,
  AuthedLeaderboardRoute: AuthedLeaderboardRoute,
  AuthedMapRoute: AuthedMapRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedProfileIndexRoute: AuthedProfileIndexRoute,
  AuthedProfileUserIdMapRoute: AuthedProfileUserIdMapRoute,
  AuthedProfileUserIdIndexRoute: AuthedProfileUserIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
